"use client";

import { useState, useTransition, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { createAdvisory, reserveAdvisory } from "@/app/academic/actions";
import type { AppRole } from "@/lib/roles";

type Session={id:string;title:string;description:string;starts_at:string;ends_at:string;capacity:number;status:string;subject_id:string|null;teacher_id:string};
type Subject={id:string;name:string;code:string};
export function AdvisoryWorkspace({sessions,subjects,reservedIds,role}:{sessions:Session[];subjects:Subject[];reservedIds:string[];role:AppRole}){
  const [message,setMessage]=useState("");const [pending,startTransition]=useTransition();const router=useRouter();
  function reserve(id:string){setMessage("");startTransition(async()=>{const result=await reserveAdvisory(id);setMessage(result.ok?"Asesoría reservada.":result.error??"No se pudo reservar.");if(result.ok)router.refresh();});}
  function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const localStart=String(form.get("startsAt"));const localEnd=String(form.get("endsAt"));form.set("startsAt",new Date(localStart).toISOString());form.set("endsAt",new Date(localEnd).toISOString());setMessage("");startTransition(async()=>{const result=await createAdvisory(form);setMessage(result.ok?"Asesoría publicada.":result.error??"No se pudo publicar.");if(result.ok){formElement.reset();router.refresh();}});}
  return <div className="module-stack">{role==="docente"&&<details className="panel material-create"><summary>Programar asesoría</summary><form className="material-form" onSubmit={create}><div className="form-grid"><label className="field"><span>Título</span><input name="title" required minLength={3} maxLength={180}/></label><label className="field"><span>Materia (opcional)</span><select name="subjectId" defaultValue=""><option value="">Sin materia</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><label className="field"><span>Inicio</span><input name="startsAt" type="datetime-local" required/></label><label className="field"><span>Fin</span><input name="endsAt" type="datetime-local" required/></label><label className="field"><span>Lugares</span><input name="capacity" type="number" min={1} max={100} defaultValue={5}/></label><label className="field fullcol"><span>Descripción</span><textarea name="description" maxLength={2000} rows={2}/></label></div><button className="button" disabled={pending}>{pending?"Publicando…":"Publicar asesoría"}</button></form></details>}
    <section className="panel"><div className="module-toolbar"><div><h2>Asesorías académicas</h2><p className="muted">Sesiones de acompañamiento publicadas por docentes.</p></div><span className="pill">{sessions.length} sesiones</span></div>{message&&<p className="form-success" role="status">{message}</p>}{!sessions.length?<div className="empty">No hay asesorías disponibles por ahora.</div>:<div className="advisory-list">{sessions.map(session=>{const reserved=reservedIds.includes(session.id);const starts=new Date(session.starts_at);return <article className="advisory-row" key={session.id}><div><span className="eyebrow">{session.status}</span><h3>{session.title}</h3><p>{session.description||"Asesoría académica"}</p><div className="material-meta"><span>{starts.toLocaleDateString("es-MX",{dateStyle:"medium"})}</span><span>{starts.toLocaleTimeString("es-MX",{timeStyle:"short"})}–{new Date(session.ends_at).toLocaleTimeString("es-MX",{timeStyle:"short"})}</span><span>{session.capacity} lugares</span></div></div>{role==="alumno"&&<button className={reserved?"button button-secondary":"button"} disabled={pending||reserved||session.status!=="Disponible"} onClick={()=>reserve(session.id)}>{reserved?"Reservada":"Reservar lugar"}</button>}</article>})}</div>}</section>
  </div>;
}
