import Link from "next/link";
import Image from "next/image";
import { redirect } from "next/navigation";
import { BookOpen, CalendarDays, ClipboardList, GraduationCap, LayoutDashboard, Megaphone, Settings, Shield, Users, UserRound, ScrollText, Library, LogOut } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { signOut } from "@/app/auth/actions";
import { MaterialSection } from "@/components/material-section";
import { AdvisorySection } from "@/components/advisory-section";
import { ReportSection } from "@/components/report-section";
import { ProfileEditor } from "@/components/profile-editor";
import { ActivityDashboard } from "@/components/activity-dashboard";
import { TeacherApplicationsWorkspace, TeacherRequestForm } from "@/components/teacher-application-workspace";
import type { AppRole } from "@/lib/roles";
import { isAppRole, roleHomes } from "@/lib/roles";

const nav: Record<AppRole,{label:string;href:string;icon:typeof LayoutDashboard}[]> = {
  alumno:[{label:"Inicio",href:"/alumno",icon:LayoutDashboard},{label:"Explorar material",href:"/alumno/explorar",icon:Library},{label:"Mis materias",href:"/alumno/materias",icon:BookOpen},{label:"Favoritos",href:"/alumno/favoritos",icon:Library},{label:"Compartir material",href:"/alumno/subir",icon:Megaphone},{label:"Mis materiales",href:"/alumno/mis-materiales",icon:Library},{label:"Asesorías",href:"/alumno/asesorias",icon:Users},{label:"Avisos",href:"/alumno/avisos",icon:Megaphone},{label:"Calificaciones",href:"/alumno/calificaciones",icon:ClipboardList},{label:"Horario",href:"/alumno/horario",icon:CalendarDays},{label:"Perfil",href:"/alumno/perfil",icon:UserRound}],
  docente:[{label:"Inicio",href:"/docente",icon:LayoutDashboard},{label:"Mis grupos",href:"/docente/grupos",icon:Users},{label:"Mis materias",href:"/docente/materias",icon:BookOpen},{label:"Materiales",href:"/docente/materiales",icon:Library},{label:"Subir material",href:"/docente/subir",icon:Megaphone},{label:"Mis materiales",href:"/docente/mis-materiales",icon:Library},{label:"Asesorías",href:"/docente/asesorias",icon:Users},{label:"Avisos",href:"/docente/avisos",icon:Megaphone},{label:"Calificaciones",href:"/docente/calificaciones",icon:ClipboardList},{label:"Alumnos",href:"/docente/alumnos",icon:GraduationCap},{label:"Horario",href:"/docente/horario",icon:CalendarDays},{label:"Estadísticas",href:"/docente/estadisticas",icon:ScrollText},{label:"Perfil",href:"/docente/perfil",icon:UserRound}],
  administrador:[{label:"Inicio",href:"/admin",icon:LayoutDashboard},{label:"Usuarios",href:"/admin/usuarios",icon:Users},{label:"Alumnos",href:"/admin/alumnos",icon:GraduationCap},{label:"Docentes",href:"/admin/docentes",icon:UserRound},{label:"Solicitudes",href:"/admin/solicitudes",icon:Shield},{label:"Materias",href:"/admin/materias",icon:BookOpen},{label:"Carreras",href:"/admin/carreras",icon:Library},{label:"Grupos",href:"/admin/grupos",icon:ClipboardList},{label:"Periodos",href:"/admin/periodos",icon:CalendarDays},{label:"Biblioteca y revisión",href:"/admin/materiales",icon:Library},{label:"Asesorías",href:"/admin/asesorias",icon:Users},{label:"Avisos",href:"/admin/avisos",icon:Megaphone},{label:"Reportes",href:"/admin/reportes",icon:ScrollText},{label:"Bitácora",href:"/admin/bitacora",icon:ScrollText},{label:"Respaldos",href:"/admin/respaldos",icon:Settings},{label:"Perfil",href:"/admin/perfil",icon:UserRound}],
};
const roleLabel:Record<AppRole,string>={alumno:"Alumno",docente:"Docente",administrador:"Administrador"};
const roleHome:Record<AppRole,string>={alumno:"alumno",docente:"docente",administrador:"admin"};

const pageInfo:Record<string,{title:string;description:string;table?:string;column?:string}>={
  materias:{title:"Materias",description:"Consulta las materias de tu actividad académica.",table:"subjects",column:"name"},calificaciones:{title:"Calificaciones",description:"Revisa el avance académico registrado.",table:"grades",column:"score"},horario:{title:"Horario",description:"Consulta las sesiones programadas.",table:"schedules",column:"starts_at"},grupos:{title:"Grupos",description:"Grupos académicos asignados.",table:"groups",column:"code"},alumnos:{title:"Alumnos",description:"Alumnado de tus grupos asignados.",table:"students",column:"control_number"},avisos:{title:"Avisos",description:"Publicaciones académicas recientes.",table:"posts",column:"title"},publicaciones:{title:"Publicaciones",description:"Avisos de la comunidad académica.",table:"posts",column:"title"},perfil:{title:"Perfil",description:"Tu información de cuenta y perfil."},usuarios:{title:"Usuarios",description:"Cuentas y permisos de la institución.",table:"profiles",column:"email"},docentes:{title:"Docentes",description:"Perfiles docentes registrados.",table:"teachers",column:"employee_number"},solicitudes:{title:"Solicitudes docentes",description:"Revisa el vínculo institucional antes de aprobar el acceso."},carreras:{title:"Carreras",description:"Programas académicos registrados.",table:"careers",column:"name"},bitacora:{title:"Bitácora",description:"Registro de accesos y actividad administrativa.",table:"access_logs",column:"event_type"},configuracion:{title:"Configuración",description:"Información general del entorno académico."},estadisticas:{title:"Estadísticas",description:"Indicadores reales de tus materiales."},reportes:{title:"Reportes",description:"Indicadores generales del Banco Académico."},respaldos:{title:"Respaldos",description:"Consulta cómo gestionar copias completas de la base de datos."},periodos:{title:"Periodos académicos",description:"Consulta los periodos configurados.",table:"academic_periods",column:"name"},explorar:{title:"Explorar material",description:"Encuentra recursos académicos aprobados."},materiales:{title:"Materiales",description:"Recursos académicos disponibles y en revisión."},subir:{title:"Compartir material",description:"Envía un recurso académico para revisión."},favoritos:{title:"Favoritos",description:"Material que guardaste para consultar después."},"mis-materiales":{title:"Mis materiales",description:"Consulta tus publicaciones y su estado."},asesorias:{title:"Asesorías",description:"Acompañamiento y apoyo académico."},
};

export async function Portal({role,section}:{role:AppRole;section?:string}) {
  const supabase=await createClient();
  const {data:{user}}=await supabase.auth.getUser();
  if(!user)redirect("/login");
  const {data:profile}=await supabase.from("profiles").select("first_name,last_name,email,role,preferred_theme,avatar_path").eq("id",user.id).maybeSingle();
  if(!isAppRole(profile?.role))redirect("/acceso-pendiente");
  if(profile.role!==role)redirect(roleHomes[profile.role]);
  const name=[profile?.first_name,profile?.last_name].filter(Boolean).join(" ")||profile?.email||user?.email||roleLabel[role];
  const firstName=profile?.first_name||"";
  const home=roleHome[role];
  const active=section;
  const title=active? pageInfo[active]?.title ?? active[0].toUpperCase()+active.slice(1) : "Inicio";
  const results=active&&pageInfo[active]?.table ? await supabase.from(pageInfo[active].table!).select(pageInfo[active].column!).limit(20) : null;
  const rowCount=results?.data?.length ?? 0;
  const admin=role==="administrador";
  const students=admin?await supabase.from("students").select("id",{count:"exact",head:true}):null;
  const teachers=admin?await supabase.from("teachers").select("id",{count:"exact",head:true}):null;
  const subjects=admin?await supabase.from("subjects").select("id",{count:"exact",head:true}):null;
  const groups=admin?await supabase.from("groups").select("id",{count:"exact",head:true}):null;
  const enrolled=role==="alumno"?await supabase.from("enrollments").select("id",{count:"exact",head:true}).eq("student_id",user!.id):null;
  const teacherGroups=role==="docente"?await supabase.from("teacher_groups").select("group_id",{count:"exact",head:true}).eq("teacher_id",user!.id):null;
  const uploadsQuery=supabase.from("materials").select("id,title,status,created_at,download_count").order("created_at",{ascending:false}).limit(100);
  const uploadRows=admin?await uploadsQuery:await uploadsQuery.eq("created_by",user!.id);
  const ownApproved=(uploadRows.data??[]).filter(item=>item.status==="Aprobado"||item.status==="Verificado").length;
  const ownPending=(uploadRows.data??[]).filter(item=>item.status==="Pendiente").length;
  const globalApproved=admin?await supabase.from("materials").select("id",{count:"exact",head:true}).in("status",["Aprobado","Verificado"]):null;
  const globalPending=admin?await supabase.from("materials").select("id",{count:"exact",head:true}).eq("status","Pendiente"):null;
  const available=role==="alumno"?await supabase.from("materials").select("id",{count:"exact",head:true}).in("status",["Aprobado","Verificado"]):null;
  const favorites=role==="alumno"?await supabase.from("material_favorites").select("material_id",{count:"exact",head:true}).eq("student_id",user!.id):null;
  const studentInfo=role==="alumno"?await supabase.from("students").select("career_id,semester,specialty").eq("id",user!.id).maybeSingle():null;
  const careerRows=role==="alumno"?await supabase.from("careers").select("id,name").eq("active",true).order("name"):null;
  const ownApplication=active==="perfil"&&role==="alumno"?await supabase.from("teacher_applications").select("id,status,employee_number,department,justification,rejection_reason,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle():null;
  const applicationRows=active==="solicitudes"&&admin?await supabase.from("teacher_applications").select("id,user_id,employee_number,department,justification,status,rejection_reason,created_at").eq("status","Pendiente").order("created_at",{ascending:true}):null;
  const applicantIds=[...new Set((applicationRows?.data??[]).map(item=>item.user_id))];
  const applicantProfiles=applicantIds.length?await supabase.from("profiles").select("id,first_name,last_name,email").in("id",applicantIds):{data:[]};
  const applicantById=new Map((applicantProfiles.data??[]).map(item=>[item.id,item]));
  const pendingApplications=(applicationRows?.data??[]).map(item=>({...item,applicant:applicantById.get(item.user_id)??null}));
  const avatar=profile?.avatar_path?await supabase.storage.from("profile-photos").createSignedUrl(profile.avatar_path,3600):null;
  const posts=await supabase.from("posts").select("id,title,body,created_at").order("created_at",{ascending:false}).limit(3);
  const hasUser=Boolean(user);
  const greeting=new Date().getHours()<12?"Buenos días":new Date().getHours()<19?"Buenas tardes":"Buenas noches";
  return <div className="app-shell" data-theme={profile?.preferred_theme??"light"}><aside className="sidebar"><Link className="brand" href={`/${home}`}><span className="brand-mark">BA</span><span>Banco Académico</span></Link><div className="institution-logos" aria-label="Identidad institucional"><a href="https://slp.tecnm.mx/identidad/" target="_blank" rel="noreferrer"><b>ITSLP</b><small>San Luis Potosí</small></a><a href="https://www.tecnm.mx/" target="_blank" rel="noreferrer"><b>TecNM</b><small>Excelencia tecnológica</small></a></div><div className="nav-label">ESPACIO {roleLabel[role].toUpperCase()}</div><nav>{nav[role].map(item=>{const Icon=item.icon;const isActive=item.href===`/${home}`?!active:item.href.endsWith(`/${active}`);return <Link key={item.href} href={item.href} className={`nav-item${isActive?" active":""}`}><Icon size={17}/><span>{item.label}</span></Link>})}</nav><div className="sidebar-bottom"><div className="profile-mini">{avatar?.data?.signedUrl?<Image className="avatar" src={avatar.data.signedUrl} width={35} height={35} unoptimized alt=""/>:<span className="avatar">{name.slice(0,1).toUpperCase()}</span>}<div><strong>{name}</strong><small>{roleLabel[role]}</small></div></div><form action={signOut}><button className="signout" type="submit"><LogOut size={15} style={{verticalAlign:"middle",marginRight:8}}/>Cerrar sesión</button></form></div></aside>
    <main className="main"><header className="header-row"><div><span className="eyebrow">{admin?"Administración":"Espacio académico"}</span><h1>{active?title:`${greeting}${firstName?`, ${firstName}`:""}`}</h1><p>{active?pageInfo[active]?.description:"Aquí tienes un resumen de tu actividad académica."}</p></div><span className="pill">{roleLabel[role]}</span></header>
      {active==="perfil"&&hasUser?<><ProfileEditor userId={user.id} firstName={profile?.first_name??""} lastName={profile?.last_name??""} email={profile?.email??user.email??""} theme={profile?.preferred_theme==="dark"?"dark":"light"} avatarUrl={avatar?.data?.signedUrl??null} student={studentInfo?.data?{careerId:studentInfo.data.career_id??"",semester:studentInfo.data.semester,specialty:studentInfo.data.specialty??""}:null} careers={careerRows?.data??[]}/>{role==="alumno"&&<TeacherRequestForm application={ownApplication?.data??null}/>}</>:active==="solicitudes"&&admin?<TeacherApplicationsWorkspace applications={pendingApplications}/>:active&&["materiales","explorar","subir","favoritos","mis-materiales"].includes(active)&&hasUser?<MaterialSection role={role} userId={user.id} favoritesOnly={active==="favoritos"} mineOnly={active==="mis-materiales"}/>:active==="asesorias"&&hasUser?<AdvisorySection role={role} userId={user.id}/>:active==="reportes"&&admin?<ReportSection/>:active==="respaldos"&&admin?<ReportSection backupInfo/>:active?<section className="panel"><div className="table-head"><h2>{title}</h2><span className="muted" style={{fontSize:12}}>Información actual</span></div>{results?.error?<div className="empty">No se pudo cargar la información. Inténtalo más tarde.</div>:rowCount===0?<div className="empty">Aún no hay información registrada aquí.</div>:<div style={{display:"grid",gridTemplateColumns:"1fr",gap:0}}>{results?.data?.map((row,index)=><div className="notice" key={index}><strong>{String((row as unknown as Record<string,unknown>)[pageInfo[active]?.column??""]??"—")}</strong></div>)}</div>}</section>:<>
        {admin?<div className="stats"><Stat label="Alumnos" value={students?.count}/><Stat label="Docentes" value={teachers?.count}/><Stat label="Materias" value={subjects?.count}/><Stat label="Grupos" value={groups?.count}/></div>:role==="alumno"?<div className="stats"><Stat label="Material disponible" value={available?.count}/><Stat label="Materias inscritas" value={enrolled?.count}/><Stat label="Favoritos" value={favorites?.count}/><Stat label="Material compartido" value={uploadRows.data?.length??0}/></div>:<div className="stats"><Stat label="Grupos asignados" value={teacherGroups?.count}/><Stat label="Materiales aprobados" value={ownApproved}/><Stat label="En revisión" value={ownPending}/><Stat label="Descargas de tus aportes" value={(uploadRows.data??[]).reduce((total,item)=>total+Number(item.download_count??0),0)}/></div>}
        {admin&&<div className="stats stats-secondary"><Stat label="Materiales aprobados" value={globalApproved?.count}/><Stat label="Pendientes de revisión" value={globalPending?.count}/></div>}
        <ActivityDashboard role={role} entries={uploadRows.data??[]} approvedCount={admin?globalApproved?.count??0:ownApproved} pendingCount={admin?globalPending?.count??0:ownPending} availableCount={available?.count??0} favoriteCount={favorites?.count??0}/>
        <section className="panel announcements"><div className="table-head"><div><span className="eyebrow">Comunidad</span><h2>Avisos recientes</h2></div><Megaphone size={18}/></div>{posts.error||!posts.data?.length?<div className="empty">No hay avisos publicados.</div>:posts.data.map(post=><article className="notice" key={post.id}><strong>{post.title}</strong><p>{post.body}</p></article>)}</section>
      </>}
    </main></div>;
}
function Stat({label,value}:{label:string;value:number|string|undefined|null}){return <div className="stat"><span>{label}</span><strong>{value??"—"}</strong><small>Datos actuales</small></div>}
